### ISSUE TITLE
[Bug]: S3 buckets always created in us-west-2 region

### ISSUE THREAD

**Issue by endrec** [aws-samples/crossplane-aws-blueprints#52]
### Welcome to AWS Blueprints for Crossplane!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-samples/crossplane-aws-blueprints/issues) and didn't find any.

### AWS Blueprints for Crossplane Release version

sha:1ab8685

### What is your environment, configuration and the example used?

Crossplane 1.9.1
crossplane/provider-aws:v0.31.0

### What did you do and What did you see instead?

Tried to create an S3 bucket in eu-west-2:
```
apiVersion: awsblueprints.io/v1alpha1
kind: ObjectStorage
metadata:
  name: my-backup
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      s3.awsblueprints.io/configuration: standard
  writeConnectionSecretToRef:
    name: bucket-info
  resourceConfig:
    providerConfigName: aws-provider
    region: eu-west-2
```

The bucket was created in us-west-2 instead.

### Additional Information

```shell
Maybe this line is related: https://github.com/aws-samples/crossplane-aws-blueprints/blob/main/compositions/aws-provider/s3/general-purpose.yaml#L46
```
